# **Feedforwarding** #

![Net Example](images/feedforwarding_example_net.png)

In [3]:
import numpy as np

In [31]:
#Input
X = np.random.randint(low=1, high= 5, size=3)
X

array([2, 4, 3])

In [32]:
#Weights 

#Because X shape is (1,3) and there are 3 nodes on Layer 1, the weights matrix should be (3 x 3).
#We'll have a matrix with the same shape as the product of WT dot X that would be the biases array (B)
W1 = np.random.rand(3,3)

#Same logic for W2 (3X4), 3 nodes from Layer 1 times 4 nodes from Layer 2
W2 = np.random.rand(3,4)

#Again, for Layer 3, (4 x 1)
W3 = np.random.rand(4,1)

print('W1')
print(W1)
print('')
print('W1')
print(W2)
print('')
print('W3')
print(W3)

W1
[[0.54561788 0.41860175 0.21813629]
 [0.9189457  0.07901461 0.77270461]
 [0.63719927 0.93520128 0.77766581]]

W1
[[0.31545192 0.31393399 0.33214544 0.1595032 ]
 [0.29211232 0.68071392 0.36608641 0.14832224]
 [0.82856723 0.15359991 0.23089978 0.27036171]]

W3
[[0.23744591]
 [0.23743104]
 [0.37898677]
 [0.18995845]]


In [33]:
#Layer 1
l1 = np.dot(W1.T,X)
l1

array([6.67861638, 3.9588658 , 5.86008845])

In [34]:
#Layer 2
l2 = np.dot(W2.T,l1)
l2

array([8.11869307, 5.69160881, 5.0206521 , 3.23679207])

In [35]:
#Layer 3
l3 = np.dot(W3.T,l2)
l3

array([5.79673175])

#### Now let's suppose that this is a classification problem, so the ouput function will be sigmoid and for this example the hidden layer will be ReLu ####

In [42]:
def ReLu(x):
    if x < 0:
        return 0
    else:
        return x
    
VReLu = np.vectorize(ReLu)

In [43]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

VSigmoid = np.vectorize(sigmoid)

In [48]:
#Putting everything together
def feedforwarding(X):
    
    l1 = VReLu(np.dot(W1.T,X))
    l2 = VReLu(np.dot(W2.T,l1))
    g = VSigmoid(np.dot(W3.T,l2))

    return g

In [47]:
feedforwarding(X)

array([0.99697173])